---
- name: check /etc/default/{{ item }} exists
  stat:
    path: "/etc/default/{{ item }}"
  register: etcdefaults_files_list
  with_items: "{{ etcdefaults_files }}"


# - name: show etcdefaults_files_list
#   debug:
#     msg: "{{ etcdefaults_files_list }}"

    
# tasks file for etcdefaults
- name: Configure /etc/default files
  remote_user: root
  template:
    src: 'etc/default/{{ item.item }}.j2'
    dest: '/etc/default/{{ item.item }}'
  loop: "{{ etcdefaults_files_list.results }}"
  when: item.stat.exists == True
  
